from django.db import models

# Create your models here.
class student(models.Model):
    name = models.CharField(max_length=10,blank=True)
    id = models.IntegerField(primary_key=True,blank=True)
    sex = models.CharField(max_length=10,blank=True)
    id_card = models.BigIntegerField(default=None,blank=True)
    family_address = models.TextField(default=None,blank=True)
    study_class = models.TextField(default=None,blank=True)
    study = models.CharField(max_length=100,blank=True)
    Class = models.IntegerField(default=None,blank=True)
    group = models.CharField(max_length=30,blank=True)
    from_beforeStudy = models.TextField(default=None,blank=True)
    study_system = models.CharField(max_length=50,blank=True)
    politics_status = models.CharField(max_length=100,blank=True)
    apartment = models.CharField(max_length=50,blank=True)
    telephone_number = models.IntegerField(default=None,blank=True)
    study_mode_before_college = models.CharField(max_length=100,default=None,blank=True)
    immigration_document_type = models.CharField(max_length=50,default=None,blank=True)
    immigration_document_number = models.IntegerField(default=None,blank=True)
    graduate_highSchool = models.CharField(max_length=100,default=None,blank=True)
    high_test_grade = models.IntegerField(default=None,blank=True)
    parents = models.BooleanField(default=None,blank=True)
    no_parents = models.BooleanField(default=None,blank=True)
    pool = models.BooleanField(default=None,blank=True)
    martyr_son = models.BooleanField(default=None,blank=True)
    only_child = models.BooleanField(default=None,blank=True)
    family_person_number = models.IntegerField(default=None,blank=True)
    family_allIn = models.CharField(max_length=50,default=None,blank=True)
    family_pool = models.BooleanField(default=None,blank=True)
    pool_reason = models.TextField(default=None)
    party_number = models.BooleanField(default=None,blank=True)
    party_membership_application = models.BooleanField(default=None, blank=True)
    teacher_name = models.CharField(max_length=100,default=None,blank=True)
    teacher_phone_number = models.BigIntegerField(default=None,blank=True)
    parents_one_name = models.CharField(max_length=100,default=None)
    parents_one_birthday = models.DateField(default=None)
    parents_one_relationship = models.CharField(max_length=100,default=None)
    parents_noe_work = models.CharField(max_length=300,default=None)
    parents_one_duty = models.CharField(max_length=200,default=None)
    parents_one_political_status = models.CharField(max_length=100,default=None)
    parents_one_phone_number = models.BigIntegerField(default=None)
    parents_one_body = models.TextField(default=None)
    parents_two_name = models.CharField(max_length=100, default=None)
    parents_two_birthday = models.DateField(default=None)
    parents_two_relationship = models.CharField(max_length=100, default=None)
    parents_two_work = models.CharField(max_length=300, default=None)
    parents_two_duty = models.CharField(max_length=200, default=None)
    parents_two_political_status = models.CharField(max_length=100, default=None)
    parents_two_phone_number = models.BigIntegerField(default=None)
    parents_two_body = models.TextField(default=None)